require "user.plugins"
require "user.auto-session"
require "user.bufferline-nvim"
require "user.coq_nvim"
require "user.editorconfig-vim"
-- require "user.galaxyline-nvim"
require "user.gitsigns-nvim"
require "user.indent-blankline-nvim"
require "user.lsp_lines-nvim"
require "user.lspsaga-nvim"
require "user.neoscroll-nvim"
require "user.null-ls-nvim"
require "user.nvim-cmp"
require "user.nvim-lastplace"
require "user.nvim-lspconfig"
require "user.nvim-tree-lua"
require "user.nvim-treesitter"
require "user.options"
require "user.project-nvim"
require "user.telescope-nvim"
require "user.theme"
require "user.toggleterm-nvim"
require "user.utils"
require "user.vim-polyglot"
require "user.which-key-nvim"
require "user.zoom"
require "user.keymaps"

-- vim.cmd "colorscheme tokyonight"
